/** DO NOT MODIFY THIS FILE. All code here are generated by MachForm Theme Editor **/

#main_body h1 a
{
background-image: url('http://ubujkykgucw.machform-trial.com/images/form_resources/machform.png');
background-repeat: no-repeat;
height: 40px;
}

html
{
background-color: #336699;
background-image: none;
}

#main_body h1
{
background-color: #6699cc;
background-image: none;
}

#form_container
{
background-color: #ffffff;
border-width: 0px;
box-shadow: none;
border-style: solid;
border-color: #336699;
}

#main_body form li.highlighted,#main_body .matrix tbody tr:hover td,#machform_review_table tr.alt
{
background-color: #ccdced;
}

#main_body form .guidelines
{
background-color: #6699cc;
border-width: 1px;
border-style: dotted;
border-color: #6699cc;
}

#main_body form .guidelines small
{
font-family: 'Ubuntu','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 400;
font-style: normal;
font-size: 80%;
color: #ffffff;
}

#main_body input.text,#main_body input.file,#main_body textarea.textarea,#main_body select.select,#main_body input.checkbox,#main_body input.radio
{
background-color: #FBFBFB;
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 400;
font-style: normal;
}

#machform_review_table td.mf_review_value
{
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 400;
font-style: normal;
}

#main_body .form_description h2,#main_body .form_success h2
{
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 600;
font-style: normal;
}

#main_body .form_description p,#main_body form ul.payment_list_items li
{
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 400;
font-style: normal;
}

#main_body form li span.ap_tp_text
{
}

#main_body label.description,#main_body span.description,#main_body .matrix caption,#main_body .matrix td.first_col,#main_body form li.total_payment span,#machform_review_table td.mf_review_label
{
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 700;
font-style: normal;
font-size: 100%;
}

#main_body form li span label,#main_body label.choice,#main_body .matrix th,#main_body form li span.symbol,.mf_sigpad_clear,#main_body form li div label,#main_body form li div span.label
{
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
}

#main_body form .section_break h3,#machform_review_table td .mf_section_title
{
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 600;
font-style: normal;
}

#main_body form .section_break p,#machform_review_table td .mf_section_content
{
font-family: 'Open Sans','Lucida Grande',Tahoma,Arial,sans-serif;
font-weight: 400;
font-style: normal;
font-size: 95%;
}

#main_body form li.section_break
{
border-top-width: 1px;
border-top-style: dotted;
border-top-color: #CCCCCC;
}

